package com.pac.dto;

import java.util.UUID;

import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class EmployeeDto {
    private String firstName;
    private String lastName;
    private String cnp;
    private String photoUrl;
    /** Kept for updates/toggles. Null on new-employee form → auto-generated by service. */
    private String badgeNumber;
    private UUID divisionId;
    private String bluetoothSecurityCode;
    private String carPlate;
    private boolean isAccessActive;
    /** Set by the controller to the currently logged-in user's UUID when accessActive=true. */
    private UUID accessGrantedBy;
}
