package com.pac.dto;

import java.util.UUID;

import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class EmployeeDto {
    private String firstName;
    private String lastName;
    private String cnp;
    private String photoUrl;
    /** Kept for updates/toggles. Null on new-employee form → auto-generated by service. */
    private String badgeNumber;
    private UUID divisionId;
    private String bluetoothSecurityCode;
    private String carPlate;
    private boolean isAccessActive;
    /**
     * Full name of the web user who granted access.
     * Stored as a plain string — avoids the FK constraint on access_granted_by
     * which references employees(id), not users(id).
     */
    private String accessGrantedByName;
}
