spring.application.name=pac

spring.datasource.url=jdbc:postgresql://${DATABASE_ID}.supabase.co:5432/PAC-Private-Access
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081


